$BROWSER=app.zen_browser.zen
$EDITOR=codium

# Opening vesktop at startup
exec = sleep 10 && vesktop
windowrulev2 = workspace 10 silent, class:^(vesktop)$

monitor=DP-2, highres@highrr, 0x0, 1.2
monitor=HDMI-A-2, highres@highrr, auto-right, 1.2
monitor=, highres@highrr, auto-right, 1.2

# Fixing "primary" monitor
workspace= name:1, monitor:DP-2
exec-once = hyprctl dispatch workspace 1

# Binding workspaces 9 and 10 to monitor 2
workspace= name:9, monitor:HDMI-A-2
workspace= name:10, monitor:HDMI-A-2

unbind = Ctrl+Shift, Escape,
bind = Ctrl+Shift, Escape, exec, kitty -o allow_remote_control=yes sh -c 'kitten @ set-spacing padding=0; btop' #btop

bind = $mainMod, M, exec, $scrPath/custom-monitor.sh #Switch second monitor

bind = $mainMod, O, exec, obsidian #Obsidian

unbind = $mainMod, F

unbind = $mainMod, C
bind = $mainMod, C, exec, $EDITOR #VS Codium

windowrulev2 = unset,class:^(vlc)$ # Fix vlc sizing

# Fixing discord popout
windowrulev2 = float,initialTitle:Discord Popout
windowrulev2 = pin,initialTitle:Discord Popout
windowrulev2 = opacity 1,initialTitle:Discord Popout
windowrulev2 = size 500 300,initialTitle:Discord Popout
windowrulev2 = move onscreen 100% 0,initialTitle:Discord Popout

# Changing mouse workspace scrolling to below as the keyboard one does
unbind = $mainMod, mouse_down
unbind = $mainMod, mouse_up
bindd = $mainMod, mouse_down, $d next workspace, workspace, r+1
bindd = $mainMod, mouse_up, $d previous workspace, workspace, r-1
binds:scroll_event_delay = 0

input {
    kb_layout = us
    kb_variant = altgr-intl
}