$BROWSER=brave
$EDITOR=codium

exec-once = iio-hyprland

monitor=eDP-1, highres@highrr, auto, 1.2
monitor=, highres@highrr, auto-up, 1.2

unbind = Ctrl+Shift, Escape,
bind = Ctrl+Shift, Escape, exec, kitty -o allow_remote_control=yes sh -c 'kitten @ set-spacing padding=0; btop' #btop

bind = $mainMod, M, exec, $scrPath/custom-monitor.sh #Switch second monitor

bind = $mainMod, O, exec, obsidian #Obsidian

unbind = $mainMod, F
bind = $mainMod, B, exec, $BROWSER #Brave

unbind = $mainMod, C
bind = $mainMod, C, exec, $EDITOR #VS Codium

# unbind = $mainMod, S
# bind = $mainMod, period, togglespecialworkspace,
# unbind = $mainMod+Alt, period
# bind = $mainMod+Alt, period, movetoworkspacesilent, special

# unbind = $mainMod, L
# bind = $mainMod, L, exec, swaylock-fancy #Lock Screen

windowrulev2 = unset,class:^(vlc)$ # Fix vlc sizing

windowrulev2 = opacity 1,floating:1 # Make floating windows not translucid (mainly bc discord webcam)

input {
    kb_layout = es,us
    kb_variant = ,intl

    touchpad {
        natural_scroll = yes
    }
}